// Prebuild step: writes site/places/_active.ts as a single-export
// re-export of the active place config. Runs before `next dev` and
// `next build` (see package.json scripts).
//
// This is the structural fix for cross-tenant string leaks. If
// lib/place.ts imported every place config and chose one at runtime,
// all five tenants' display names would be inlined into the client
// bundle — and "I live in Harpenden" would silently render on York.
// By importing only _active.ts, the build contains exactly one
// place's strings. Period.

import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const slug = process.env.NEXT_PUBLIC_PLACE_SLUG;

if (!slug) {
  console.error(
    "NEXT_PUBLIC_PLACE_SLUG is not set. Every dev/build must set it " +
      "(e.g. NEXT_PUBLIC_PLACE_SLUG=york bun dev).",
  );
  process.exit(1);
}

const root = resolve(import.meta.dirname, "..");
const placeFile = resolve(root, "places", `${slug}.ts`);

if (!existsSync(placeFile)) {
  console.error(`No place config found at places/${slug}.ts`);
  process.exit(1);
}

// Each place config exports a named const matching its camelCased slug.
// e.g. places/york.ts -> `export const york = {...}`
// e.g. places/suffolk-menta.ts -> `export const suffolkMenta = {...}`
const camelExport = slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

const activeFile = resolve(root, "places", "_active.ts");
const contents = `// AUTO-GENERATED by scripts/select-place.ts — do not edit by hand.
// Slug at build time: ${slug}
import { ${camelExport} } from "./${slug}";
export const activePlace = ${camelExport};
`;

writeFileSync(activeFile, contents);
console.log(`select-place: wrote places/_active.ts for slug "${slug}"`);
